services:
  - type: web
    name: retreatsos-api
    runtime: docker
    repo: <YOUR_GITHUB_REPO_URL>
    branch: main
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_URL
        sync: false
      - key: PORT
        value: "8080"
    healthCheckPath: /health
databases:
  - name: retreatsos-db
    plan: free
